version: '3'
services:
  dev:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass123
  # test:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - '5433:5432'
  #   environment:
  #     POSTGRES_PASSWORD: pass123
